#!/bin/bash
# Hook de pre-commit para actualizar el diagrama PlantUML y la imagen PNG

# Ruta al archivo PlantUML
PLANTUML_FILE="doc/classes_diagram.puml"
PNG_FILE="doc/classes_processing.png"

# Verifica si algún archivo .pde ha cambiado
if git diff --cached --name-only | grep -q "\.pde$"; then
    echo "Actualizando el archivo PlantUML desde los ficheros .pde..."
    ./scripts/generate_plantuml.sh
    git add "$PLANTUML_FILE"
fi

# Verifica si el archivo PlantUML ha cambiado
if git diff --cached --name-only | grep -q "$PLANTUML_FILE"; then
    echo "Actualizando el diagrama PNG desde $PLANTUML_FILE..."
    
    # Detectar sistema operativo usando OSTYPE
    if [[ "$OSTYPE" == "msys" ]]; then
        # Windows (Git Bash)
        /c/java/jdk-11.0.20+8/bin/java.exe -jar /c/plantuml/plantuml.jar "$PLANTUML_FILE" -o "$(pwd)/doc"
    else
        # macOS/Linux
        plantuml "$PLANTUML_FILE" -o "$(pwd)/doc"
    fi
    
    git add "$PNG_FILE"
fi