@startuml classes_processing

' Declaración de las clases en Processing
class Burbujas {
    +void settings()
    +void setup()
    +void draw()
    +void mousePressed()
    +void serialEvent(Serial port)
}

class Particula {
    +void run()
    +void update()
    +void aplicarFuerza(PVector f)
    +void aplicarViscosidad(float v)
    +void render()
}

class SistemaParticulas {
    +void addParticula()
    +void addParticula(int n)
    +void run()
}

' Relaciones entre las clases
SistemaParticulas --> Particula : contiene

@enduml
