@startuml clases_processing

' Declaración de las clases en Processing
class Burbujas {
    +void settings()
    +void setup()
    +void draw()
    +void mousePressed()
    +void serialEvent(Serial)
}

class Particula {
    +PVector posicion
    +PVector velocidad
    +PVector aceleracion
    +float tamanio
    +boolean isDead
    +void run()
    +void update()
    +void aplicarFuerza(PVector)
    +void aplicarViscosidad(float)
    +void render()
}

class SistemaParticulas {
    +ArrayList<Particula> particulas
    +PVector origin
    +float viscosidad
    +void addParticula()
    +void addParticula(int)
    +void run()
}

' Relaciones entre las clases
' Burbujas --> SistemaParticulas : usa
SistemaParticulas --> Particula : contiene

@enduml